### ISSUE TITLE
[tn] support english text norm 英文tn支持计划

### ISSUE THREAD

**Issue by xingchensong** [wenet-e2e/WeTextProcessing#202]
# NOTE
并不只是简单照搬nemo的规则，在其基础上进行了简化，fst编译时间从460s降低到56s，fst大小从40M降低到4M，同时基本功能依旧

# 高优

- [x] basic component, like cardinal and word (整数，12345) https://github.com/wenet-e2e/WeTextProcessing/pull/203  @xingchensong 
- [x] ordinal  (序数，1st -> first)  https://github.com/wenet-e2e/WeTextProcessing/pull/204  @xingchensong 
- [x] date (日期，2024/04/03)   https://github.com/wenet-e2e/WeTextProcessing/pull/205  @xingchensong 
- [x] decimal (小数，12.01 dollers)  https://github.com/wenet-e2e/WeTextProcessing/pull/207  @xingchensong 
- [x] fraction (分数，1/2)  https://github.com/wenet-e2e/WeTextProcessing/pull/209  @xingchensong 
- [x] time （时间，2:30 a.m.）https://github.com/wenet-e2e/WeTextProcessing/pull/210  @xingchensong 
- [x] measure  (量词，23kg)  https://github.com/wenet-e2e/WeTextProcessing/pull/211  @xingchensong 
- [x] money （钱，$23）  https://github.com/wenet-e2e/WeTextProcessing/pull/212   @xingchensong 
- [x] whitelist  (白名单)  https://github.com/wenet-e2e/WeTextProcessing/pull/206  https://github.com/wenet-e2e/WeTextProcessing/pull/216   @whiteshirt0429 

# 低优
- [x] telephone  (电话号码，010-2345-232323)  https://github.com/wenet-e2e/WeTextProcessing/pull/213  @xingchensong 
- [x] electronic  (URLs, email addresses，cdf1@abc.edu)  https://github.com/wenet-e2e/WeTextProcessing/pull/214  @xingchensong 
- [x] roman (罗马数字，IV->four)  https://github.com/wenet-e2e/WeTextProcessing/pull/215

# 低低优 (暂时可以不实现)
~~serial (数字和字母，特殊字符组合，c2365-zh)~~
~~range  (范围, 10% to 20%)~~

ref: 
- build_tagger(): https://github.com/NVIDIA/NeMo-text-processing/tree/main/nemo_text_processing/text_normalization/en/taggers
- buid_verbalizer(): https://github.com/NVIDIA/NeMo-text-processing/tree/main/nemo_text_processing/text_normalization/en/verbalizers

# TODO
- [x] c++ runtime 适配  https://github.com/wenet-e2e/WeTextProcessing/pull/219  https://github.com/wenet-e2e/WeTextProcessing/pull/220
- [x] 编译优化，目前编译时间接近十分钟，fst过大，超过40M  https://github.com/wenet-e2e/WeTextProcessing/pull/221

# BUGFIX
- https://github.com/wenet-e2e/WeTextProcessing/pull/224
- https://github.com/wenet-e2e/WeTextProcessing/pull/225
- https://github.com/wenet-e2e/WeTextProcessing/pull/226
- https://github.com/wenet-e2e/WeTextProcessing/pull/227
- https://github.com/wenet-e2e/WeTextProcessing/pull/228
